services:
  nginx:
    build:
      context: .  # Dockerfile이 있는 디렉터리 경로 (현재 디렉터리)
      dockerfile: Main_Nginx_Dockerfile  # Main_Nginx_Dockerfile 이름 (기본적으로 'Main_Nginx_Dockerfile'이므로 생략 가능)
      args:
        DOMAINS: "seoktae.duckdns.org" # 여기에서 배열은 띄어쓰기로 구분
    container_name: main_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sites-available/:/etc/nginx/sites-available  # 현재 디렉토리 기준
      - ./nginx.conf:/etc/nginx/nginx.conf  # 현재 디렉토리 기준
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh  # 호스트의 entrypoint.sh를 컨테이너에 마운트
    entrypoint: [ "/bin/bash", "/usr/local/bin/entrypoint.sh" ]  # entrypoint.sh 실행
    restart: always

