# nginx 시작전에 Certbot 이 먼저 실행되야함
version: '3'
services:
  nginx:
    build:
      dockerfile: ../../nginx/dockerfiles/main_nginx_Dockerfile   # main_nginx_Dockerfile 이름 (기본적으로 'main_nginx_Dockerfile'이므로 생략 가능)
      args:
        DOMAINS: "seoktae.online " # 사용할 도메인 배열 [여기에서 배열은 띄어쓰기로 구분]
        EMAIL: "dhstjrxo123@gmail.com" # 이메일
    container_name: main_nginx
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ../../nginx/sites-available/:/etc/nginx/sites-available  # 현재 디렉토리 기준
      - ../../nginx/config/nginx.conf:/etc/nginx/nginx.conf  # 현재 디렉토리 기준
      - ../../nginx/scripts/entrypoint.sh:/usr/local/bin/entrypoint.sh  # 호스트의 entrypoint.sh를 컨테이너에 마운트
      - ../../certbot/config/certbot-webroot:/var/www/certbot  # 인증서 검증을 위한 웹 루트
      - ../../certbot/config/etc/letsencrypt:/etc/letsencrypt  # 인증서 저장 경로
    entrypoint: [ "/bin/bash", "/usr/local/bin/entrypoint.sh" ]  # entrypoint.sh 실행
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always