# 깃헙 Action Trigger CICD
name: CI
# 이름이 "main" 인 브랜치가 "push" or "pull_request" 가 요청되었을때 실행하겠다.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 읽기 권한을 부여하겠다.
permissions:
  contents: read

# Job 리스트
jobs:
  # 1반쩨 job = 빌드
  build:
    runs-on: ubuntu-latest # 우분투 최신버전을 사용하겠다
    steps:
      - name: Docker compose
        uses: appleboy/ssh-action@master # 깃헙액션에 제공해주는 appleboy 에있는 ssh-action@master 라는 모듈을 사용하겠다.
        with:
            # 우분투를 사용하겠다
          username: ubuntu
          host: ${{ secrets.SPRING_BOOT_DOCKER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring_none_stop_deploy_docker:latest
            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d