# 깃헙 Action Trigger CICD
name: CI

env:
  SERVER_IP: ${{secrets.SERVER_IP}}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  DOCKER_DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  PLATFORM: "react"
  BLUE: "blue"
  GREEN: "green"
  BLUE_PORT: 3000
  GREEN_PORT: 3001
  REACT_HC_PORT: 81


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 읽기 권한을 부여하겠다.
permissions:
  contents: read

# Job 리스트
jobs:
  # 1반쩨 job = 빌드
  build:
    runs-on: ubuntu-latest # 우분투 최신버전을 사용하겠다
    steps:
      # 도커 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      # 도커 push
      - name: Build Docker
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/main_server .

      - name: Push Docker
        # 위에서 카피한 .jar 파일과 설정들을 Docker Hub 로 Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/main_server:latest

      # SSH 접속해서 docker compose 실행
      - name: Docker compose
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ env.SERVER_IP }}
          key: ${{ env.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker pull ${{ env.DOCKER_DOCKERHUB_USERNAME }}/main_server:latest


